# Generated by Django 4.2.3 on 2023-07-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smalldogs',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
