# Generated by Django 4.2.3 on 2023-07-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_smalldogs_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='LargeDogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('breed', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=1)),
                ('age', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
